### ISSUE TITLE
Issue when testing a webcomponent customelement from a design system

### ISSUE THREAD

**Issue by squidjam** [NickColley/jest-axe#268]
Hi.
First of all, thanks, excellent work.

I've found an issue that passes the test when there's a message that makes me think it's not testing for the component rendered completely.

I'm using Clarity from VMware in conjunction with React ([repo here](https://github.com/vmware-clarity/core)).  
Using the method described in the readme alongside @testing-library/react.

```
import { CdsButton } from "@cds/react/button";
import { axe, toHaveNoViolations } from 'jest-axe';
import { cleanup, render } from '@testing-library/react';

it('should not have basic accessibility issues', async () => {
  const { container } = await render(<CdsButton>Button</CdsButton>
  const results = await axe(container)
  expect(results).toHaveNoViolations()
}
```
But I get this message when I run the test:
```
Couldn't load preload assets:  TypeError: Cannot read properties of null (reading 'href')
    at X:\Projects\poc_clarity_jest-axe\node_modules\axe-core\axe.js:12600:20
    at Array.filter (<anonymous>)
    at filterStylesheetsWithSameHref (X:\Projects\poc_clarity_jest-axe\node_modules\axe-core\axe.js:12599:21)
    at getStylesheetsOfRootNode (X:\Projects\poc_clarity_jest-axe\node_modules\axe-core\axe.js:12559:14)
    at X:\Projects\poc_clarity_jest-axe\node_modules\axe-core\axe.js:12527:22
    at Array.forEach (<anonymous>)
    at getCssomForAllRootNodes (X:\Projects\poc_clarity_jest-axe\node_modules\axe-core\axe.js:12525:17)
    at Object.preloadCssom [as cssom] (X:\Projects\poc_clarity_jest-axe\node_modules\axe-core\axe.js:12502:14)
    at X:\Projects\poc_clarity_jest-axe\node_modules\axe-core\axe.js:12695:44
    at Array.map (<anonymous>)
```

Could this be an issue or am I missing something?

**Comment by NickColley** [comment]
Please check this is failing on version 8 and re-open if it is and I'll look into it when I have time, cheers.
